### ISSUE TITLE
sbt problem

### ISSUE THREAD

**Issue by florian-rabe** [UniFormal/ESSLLI2019#1]
One of you had this problem while running sbt:

sbt deploy

[info] Loading settings for project src-build from plugins.sbt,project.sbt ...

[info] Loading project definition from /Users/sorenschlassa/MMT/src/project

[info] Updating ProjectRef(uri("file:/Users/sorenschlassa/MMT/src/project/"), "src-build")...

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

[warn] 	::          UNRESOLVED DEPENDENCIES         ::

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

[warn] 	:: org.scalastyle#scalastyle-sbt-plugin;1.0.0: Resolution failed several times for dependency: org.scalastyle#scalastyle-sbt-plugin;1.0.0 {compile=[default(compile)]}:: 

[warn] 	typesafe-ivy-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[warn] 	sbt-plugin-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[warn] 	typesafe-ivy-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/1.0.0/jars/scalastyle-sbt-plugin.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[warn] 	typesafe-ivy-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/1.0.0/jars/scalastyle-sbt-plugin.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[warn] 	:: com.eed3si9n#sbt-unidoc;0.4.1: Resolution failed several times for dependency: com.eed3si9n#sbt-unidoc;0.4.1 {compile=[default(compile)]}:: 

[warn] 	typesafe-ivy-releases: unable to get resource for com.eed3si9n#sbt-unidoc;0.4.1: res=https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[warn] 	sbt-plugin-releases: unable to get resource for com.eed3si9n#sbt-unidoc;0.4.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[warn] 	:: com.eed3si9n#sbt-assembly;0.14.6: Resolution failed several times for dependency: com.eed3si9n#sbt-assembly;0.14.6 {compile=[default(compile)]}:: 

[warn] 	typesafe-ivy-releases: unable to get resource for com.eed3si9n#sbt-assembly;0.14.6: res=https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.14.6/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[warn] 	sbt-plugin-releases: unable to get resource for com.eed3si9n#sbt-assembly;0.14.6: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.14.6/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[warn] 	:: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: Resolution failed several times for dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4 {compile=[default(compile)]}:: 

[warn] 	typesafe-ivy-releases: unable to get resource for com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: res=https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[warn] 	sbt-plugin-releases: unable to get resource for com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

[warn] 

[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.

[warn] 		org.scalastyle:scalastyle-sbt-plugin:1.0.0 (scalaVersion=2.12, sbtVersion=1.0)

[warn] 		com.eed3si9n:sbt-unidoc:0.4.1 (scalaVersion=2.12, sbtVersion=1.0)

[warn] 		com.eed3si9n:sbt-assembly:0.14.6 (scalaVersion=2.12, sbtVersion=1.0)

[warn] 		com.typesafe.sbteclipse:sbteclipse-plugin:5.2.4 (scalaVersion=2.12, sbtVersion=1.0)

[warn] 

[warn] 	Note: Unresolved dependencies path:

[warn] 		org.scalastyle:scalastyle-sbt-plugin:1.0.0 (scalaVersion=2.12, sbtVersion=1.0) (/Users/sorenschlassa/MMT/src/project/plugins.sbt#L3-4)

[warn] 		  +- default:src-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)

[warn] 		com.eed3si9n:sbt-unidoc:0.4.1 (scalaVersion=2.12, sbtVersion=1.0) (/Users/sorenschlassa/MMT/src/project/plugins.sbt#L5-6)

[warn] 		  +- default:src-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)

[warn] 		com.eed3si9n:sbt-assembly:0.14.6 (scalaVersion=2.12, sbtVersion=1.0) (/Users/sorenschlassa/MMT/src/project/plugins.sbt#L6-7)

[warn] 		  +- default:src-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)

[warn] 		com.typesafe.sbteclipse:sbteclipse-plugin:5.2.4 (scalaVersion=2.12, sbtVersion=1.0) (/Users/sorenschlassa/MMT/src/project/plugins.sbt#L8-9)

[warn] 		  +- default:src-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)

[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scalastyle#scalastyle-sbt-plugin;1.0.0: Resolution failed several times for dependency: org.scalastyle#scalastyle-sbt-plugin;1.0.0 {compile=[default(compile)]}:: 

[error] 	typesafe-ivy-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	sbt-plugin-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	typesafe-ivy-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/1.0.0/jars/scalastyle-sbt-plugin.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	typesafe-ivy-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/1.0.0/jars/scalastyle-sbt-plugin.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 

[error] unresolved dependency: com.eed3si9n#sbt-unidoc;0.4.1: Resolution failed several times for dependency: com.eed3si9n#sbt-unidoc;0.4.1 {compile=[default(compile)]}:: 

[error] 	typesafe-ivy-releases: unable to get resource for com.eed3si9n#sbt-unidoc;0.4.1: res=https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	sbt-plugin-releases: unable to get resource for com.eed3si9n#sbt-unidoc;0.4.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 

[error] unresolved dependency: com.eed3si9n#sbt-assembly;0.14.6: Resolution failed several times for dependency: com.eed3si9n#sbt-assembly;0.14.6 {compile=[default(compile)]}:: 

[error] 	typesafe-ivy-releases: unable to get resource for com.eed3si9n#sbt-assembly;0.14.6: res=https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.14.6/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	sbt-plugin-releases: unable to get resource for com.eed3si9n#sbt-assembly;0.14.6: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.14.6/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 

[error] unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: Resolution failed several times for dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4 {compile=[default(compile)]}:: 

[error] 	typesafe-ivy-releases: unable to get resource for com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: res=https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	sbt-plugin-releases: unable to get resource for com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 

[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)

[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)

[error] 	at sbt.internal.librarymanagement.IvyActions$$$Lambda$2046/2102670054.apply(Unknown Source)

[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)

[error] 	at sbt.internal.librarymanagement.IvySbt$Module$$Lambda$2047/2028935944.apply(Unknown Source)

[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)

[error] 	at sbt.internal.librarymanagement.IvySbt$$Lambda$2048/1742855735.apply(Unknown Source)

[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)

[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)

[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)

[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)

[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)

[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)

[error] 	at xsbt.boot.Using$.apply(Using.scala:9)

[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)

[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)

[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)

[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)

[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)

[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)

[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)

[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)

[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)

[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)

[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)

[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)

[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)

[error] 	at sbt.internal.LibraryManagement$$$Lambda$2042/15614067.apply(Unknown Source)

[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)

[error] 	at sbt.util.Tracked$$$Lambda$1995/210783352.apply(Unknown Source)

[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)

[error] 	at sbt.internal.LibraryManagement$$$Lambda$2044/2127972338.apply(Unknown Source)

[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)

[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)

[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)

[error] 	at sbt.internal.LibraryManagement$$$Lambda$2041/1165783538.apply(Unknown Source)

[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)

[error] 	at sbt.util.Tracked$$$Lambda$1952/381561154.apply(Unknown Source)

[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)

[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)

[error] 	at sbt.Classpaths$$$Lambda$1126/1845746463.apply(Unknown Source)

[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)

[error] 	at scala.Function1$$Lambda$1015/1917860633.apply(Unknown Source)

[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)

[error] 	at sbt.internal.util.$tilde$greater$$Lambda$1866/1955991197.apply(Unknown Source)

[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)

[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)

[error] 	at sbt.Execute$$Lambda$1882/1674882807.apply(Unknown Source)

[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)

[error] 	at sbt.Execute.work(Execute.scala:278)

[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)

[error] 	at sbt.Execute$$Lambda$1874/1133731484.apply(Unknown Source)

[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)

[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$1881/177267393.apply(Unknown Source)

[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)

[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

[error] 	at java.lang.Thread.run(Thread.java:745)

[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: org.scalastyle#scalastyle-sbt-plugin;1.0.0: Resolution failed several times for dependency: org.scalastyle#scalastyle-sbt-plugin;1.0.0 {compile=[default(compile)]}:: 

[error] 	typesafe-ivy-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	sbt-plugin-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	typesafe-ivy-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/1.0.0/jars/scalastyle-sbt-plugin.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	typesafe-ivy-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scalastyle/scalastyle-sbt-plugin/1.0.0/jars/scalastyle-sbt-plugin.jar: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 

[error] unresolved dependency: com.eed3si9n#sbt-unidoc;0.4.1: Resolution failed several times for dependency: com.eed3si9n#sbt-unidoc;0.4.1 {compile=[default(compile)]}:: 

[error] 	typesafe-ivy-releases: unable to get resource for com.eed3si9n#sbt-unidoc;0.4.1: res=https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	sbt-plugin-releases: unable to get resource for com.eed3si9n#sbt-unidoc;0.4.1: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 

[error] unresolved dependency: com.eed3si9n#sbt-assembly;0.14.6: Resolution failed several times for dependency: com.eed3si9n#sbt-assembly;0.14.6 {compile=[default(compile)]}:: 

[error] 	typesafe-ivy-releases: unable to get resource for com.eed3si9n#sbt-assembly;0.14.6: res=https://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.14.6/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	sbt-plugin-releases: unable to get resource for com.eed3si9n#sbt-assembly;0.14.6: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.14.6/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 

[error] unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: Resolution failed several times for dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4 {compile=[default(compile)]}:: 

[error] 	typesafe-ivy-releases: unable to get resource for com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: res=https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[error] 	sbt-plugin-releases: unable to get resource for com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

**Comment by ComFreek** [comment]
The core error is probably this one

> [warn] sbt-plugin-releases: unable to get resource for org.scalastyle#scalastyle-sbt-plugin;1.0.0: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalastyle/scalastyle-sbt-plugin/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Indeed, googling `sbt PKIX path building failed` brings many results. I'd suggest trying all the answers from [this StackOverflow question](https://stackoverflow.com/q/41981320/603003). Are you (or the student) perhaps behind a corporate/university proxy messing with TLS certificates?
